// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartBeat.proto

package cn.weit.happymo.protobuf;

public final class HeartBeatInfo {
  private HeartBeatInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.weit.happymo.protobuf.HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
     */
    cn.weit.happymo.protobuf.MsgTypeEnum.MsgType getMsgType();
  }
  /**
   * Protobuf type {@code cn.weit.happymo.protobuf.HeartBeat}
   */
  public  static final class HeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.weit.happymo.protobuf.HeartBeat)
      HeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeat() {
      msgType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.weit.happymo.protobuf.HeartBeatInfo.internal_static_cn_weit_happymo_protobuf_HeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.weit.happymo.protobuf.HeartBeatInfo.internal_static_cn_weit_happymo_protobuf_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.class, cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.Builder.class);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
     */
    public cn.weit.happymo.protobuf.MsgTypeEnum.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      cn.weit.happymo.protobuf.MsgTypeEnum.MsgType result = cn.weit.happymo.protobuf.MsgTypeEnum.MsgType.valueOf(msgType_);
      return result == null ? cn.weit.happymo.protobuf.MsgTypeEnum.MsgType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != cn.weit.happymo.protobuf.MsgTypeEnum.MsgType.HEARTBEAT.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != cn.weit.happymo.protobuf.MsgTypeEnum.MsgType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat)) {
        return super.equals(obj);
      }
      cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat other = (cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat) obj;

      if (msgType_ != other.msgType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.weit.happymo.protobuf.HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.weit.happymo.protobuf.HeartBeat)
        cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.weit.happymo.protobuf.HeartBeatInfo.internal_static_cn_weit_happymo_protobuf_HeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.weit.happymo.protobuf.HeartBeatInfo.internal_static_cn_weit_happymo_protobuf_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.class, cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.Builder.class);
      }

      // Construct using cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.weit.happymo.protobuf.HeartBeatInfo.internal_static_cn_weit_happymo_protobuf_HeartBeat_descriptor;
      }

      @java.lang.Override
      public cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat getDefaultInstanceForType() {
        return cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat build() {
        cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat buildPartial() {
        cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat result = new cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat(this);
        result.msgType_ = msgType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat) {
          return mergeFrom((cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat other) {
        if (other == cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
       */
      public cn.weit.happymo.protobuf.MsgTypeEnum.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        cn.weit.happymo.protobuf.MsgTypeEnum.MsgType result = cn.weit.happymo.protobuf.MsgTypeEnum.MsgType.valueOf(msgType_);
        return result == null ? cn.weit.happymo.protobuf.MsgTypeEnum.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
       */
      public Builder setMsgType(cn.weit.happymo.protobuf.MsgTypeEnum.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.weit.happymo.protobuf.MsgType msgType = 1;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.weit.happymo.protobuf.HeartBeat)
    }

    // @@protoc_insertion_point(class_scope:cn.weit.happymo.protobuf.HeartBeat)
    private static final cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat();
    }

    public static cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
      @java.lang.Override
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.weit.happymo.protobuf.HeartBeatInfo.HeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_weit_happymo_protobuf_HeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_weit_happymo_protobuf_HeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017HeartBeat.proto\022\030cn.weit.happymo.proto" +
      "buf\032\rMsgType.proto\"?\n\tHeartBeat\0222\n\007msgTy" +
      "pe\030\001 \001(\0162!.cn.weit.happymo.protobuf.MsgT" +
      "ypeB\017B\rHeartBeatInfoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.weit.happymo.protobuf.MsgTypeEnum.getDescriptor(),
        }, assigner);
    internal_static_cn_weit_happymo_protobuf_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_weit_happymo_protobuf_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_weit_happymo_protobuf_HeartBeat_descriptor,
        new java.lang.String[] { "MsgType", });
    cn.weit.happymo.protobuf.MsgTypeEnum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
