// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MoRequest.proto

package cn.weit.happymo.message;

public final class MoRequest {
  private MoRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MoRequestMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.weit.happymo.message.MoRequestMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 msgId = 1;</code>
     */
    int getMsgId();

    /**
     * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
     */
    MsgTypeEnum.MsgType getMsgType();

    /**
     * <code>int32 version = 3;</code>
     */
    int getVersion();

    /**
     * <code>string serverName = 4;</code>
     */
    String getServerName();
    /**
     * <code>string serverName = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <code>string apiUrl = 5;</code>
     */
    String getApiUrl();
    /**
     * <code>string apiUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getApiUrlBytes();

    /**
     * <code>string method = 6;</code>
     */
    String getMethod();
    /**
     * <code>string method = 6;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>string ip = 7;</code>
     */
    String getIp();
    /**
     * <code>string ip = 7;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 8;</code>
     */
    int getPort();

    /**
     * <code>.cn.weit.happymo.message.State state = 9;</code>
     */
    int getStateValue();
    /**
     * <code>.cn.weit.happymo.message.State state = 9;</code>
     */
    ServerState.State getState();

    /**
     * <code>int64 updateTime = 10;</code>
     */
    long getUpdateTime();

    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */
    int getMapCount();
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */
    boolean containsMap(
            String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getMap();
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */
    java.util.Map<String, String>
    getMapMap();
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */

    String getMapOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */

    String getMapOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code cn.weit.happymo.message.MoRequestMsg}
   */
  public  static final class MoRequestMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.weit.happymo.message.MoRequestMsg)
      MoRequestMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MoRequestMsg.newBuilder() to construct.
    private MoRequestMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoRequestMsg() {
      msgType_ = 0;
      serverName_ = "";
      apiUrl_ = "";
      method_ = "";
      ip_ = "";
      state_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MoRequestMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 24: {

              version_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              serverName_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              apiUrl_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 64: {

              port_ = input.readInt32();
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 80: {

              updateTime_ = input.readInt64();
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000400) != 0)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000400;
              }
              com.google.protobuf.MapEntry<String, String>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MoRequest.internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 11:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MoRequest.internal_static_cn_weit_happymo_message_MoRequestMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MoRequest.MoRequestMsg.class, MoRequest.MoRequestMsg.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <code>int32 msgId = 1;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
     */
    public MsgTypeEnum.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      MsgTypeEnum.MsgType result = MsgTypeEnum.MsgType.valueOf(msgType_);
      return result == null ? MsgTypeEnum.MsgType.UNRECOGNIZED : result;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int SERVERNAME_FIELD_NUMBER = 4;
    private volatile Object serverName_;
    /**
     * <code>string serverName = 4;</code>
     */
    public String getServerName() {
      Object ref = serverName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      }
    }
    /**
     * <code>string serverName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APIURL_FIELD_NUMBER = 5;
    private volatile Object apiUrl_;
    /**
     * <code>string apiUrl = 5;</code>
     */
    public String getApiUrl() {
      Object ref = apiUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        apiUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string apiUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getApiUrlBytes() {
      Object ref = apiUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        apiUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 6;
    private volatile Object method_;
    /**
     * <code>string method = 6;</code>
     */
    public String getMethod() {
      Object ref = method_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 7;
    private volatile Object ip_;
    /**
     * <code>string ip = 7;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 8;
    private int port_;
    /**
     * <code>int32 port = 8;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int STATE_FIELD_NUMBER = 9;
    private int state_;
    /**
     * <code>.cn.weit.happymo.message.State state = 9;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.cn.weit.happymo.message.State state = 9;</code>
     */
    public ServerState.State getState() {
      @SuppressWarnings("deprecation")
      ServerState.State result = ServerState.State.valueOf(state_);
      return result == null ? ServerState.State.UNRECOGNIZED : result;
    }

    public static final int UPDATETIME_FIELD_NUMBER = 10;
    private long updateTime_;
    /**
     * <code>int64 updateTime = 10;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    public static final int MAP_FIELD_NUMBER = 11;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  MoRequest.internal_static_cn_weit_happymo_message_MoRequestMsg_MapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> map_;
    private com.google.protobuf.MapField<String, String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */

    public boolean containsMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */

    public java.util.Map<String, String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */

    public String getMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map = 11;</code>
     */

    public String getMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0) {
        output.writeInt32(1, msgId_);
      }
      if (msgType_ != MsgTypeEnum.MsgType.HEARTBEAT.getNumber()) {
        output.writeEnum(2, msgType_);
      }
      if (version_ != 0) {
        output.writeInt32(3, version_);
      }
      if (!getServerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serverName_);
      }
      if (!getApiUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, apiUrl_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, method_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(8, port_);
      }
      if (state_ != ServerState.State.Alive.getNumber()) {
        output.writeEnum(9, state_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(10, updateTime_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMap(),
          MapDefaultEntryHolder.defaultEntry,
          11);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      if (msgType_ != MsgTypeEnum.MsgType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgType_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      if (!getServerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serverName_);
      }
      if (!getApiUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, apiUrl_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, method_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, port_);
      }
      if (state_ != ServerState.State.Alive.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, state_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, updateTime_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(11, map__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MoRequest.MoRequestMsg)) {
        return super.equals(obj);
      }
      MoRequest.MoRequestMsg other = (MoRequest.MoRequestMsg) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (msgType_ != other.msgType_) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getServerName()
          .equals(other.getServerName())) return false;
      if (!getApiUrl()
          .equals(other.getApiUrl())) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (state_ != other.state_) return false;
      if (getUpdateTime()
          != other.getUpdateTime()) return false;
      if (!internalGetMap().equals(
          other.internalGetMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getServerName().hashCode();
      hash = (37 * hash) + APIURL_FIELD_NUMBER;
      hash = (53 * hash) + getApiUrl().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MoRequest.MoRequestMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MoRequest.MoRequestMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MoRequest.MoRequestMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MoRequest.MoRequestMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MoRequest.MoRequestMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MoRequest.MoRequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MoRequest.MoRequestMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.weit.happymo.message.MoRequestMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.weit.happymo.message.MoRequestMsg)
        MoRequest.MoRequestMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MoRequest.internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 11:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 11:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MoRequest.internal_static_cn_weit_happymo_message_MoRequestMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MoRequest.MoRequestMsg.class, MoRequest.MoRequestMsg.Builder.class);
      }

      // Construct using cn.weit.happymo.message.MoRequest.MoRequestMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0;

        msgType_ = 0;

        version_ = 0;

        serverName_ = "";

        apiUrl_ = "";

        method_ = "";

        ip_ = "";

        port_ = 0;

        state_ = 0;

        updateTime_ = 0L;

        internalGetMutableMap().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MoRequest.internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor;
      }

      @Override
      public MoRequest.MoRequestMsg getDefaultInstanceForType() {
        return MoRequest.MoRequestMsg.getDefaultInstance();
      }

      @Override
      public MoRequest.MoRequestMsg build() {
        MoRequest.MoRequestMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MoRequest.MoRequestMsg buildPartial() {
        MoRequest.MoRequestMsg result = new MoRequest.MoRequestMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.msgId_ = msgId_;
        result.msgType_ = msgType_;
        result.version_ = version_;
        result.serverName_ = serverName_;
        result.apiUrl_ = apiUrl_;
        result.method_ = method_;
        result.ip_ = ip_;
        result.port_ = port_;
        result.state_ = state_;
        result.updateTime_ = updateTime_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MoRequest.MoRequestMsg) {
          return mergeFrom((MoRequest.MoRequestMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MoRequest.MoRequestMsg other) {
        if (other == MoRequest.MoRequestMsg.getDefaultInstance()) return this;
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getServerName().isEmpty()) {
          serverName_ = other.serverName_;
          onChanged();
        }
        if (!other.getApiUrl().isEmpty()) {
          apiUrl_ = other.apiUrl_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MoRequest.MoRequestMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MoRequest.MoRequestMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgId_ ;
      /**
       * <code>int32 msgId = 1;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>int32 msgId = 1;</code>
       */
      public Builder setMsgId(int value) {

        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgId = 1;</code>
       */
      public Builder clearMsgId() {

        msgId_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
       */
      public MsgTypeEnum.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        MsgTypeEnum.MsgType result = MsgTypeEnum.MsgType.valueOf(msgType_);
        return result == null ? MsgTypeEnum.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
       */
      public Builder setMsgType(MsgTypeEnum.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.weit.happymo.message.MsgType msgType = 2;</code>
       */
      public Builder clearMsgType() {

        msgType_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 3;</code>
       */
      public Builder setVersion(int value) {

        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 3;</code>
       */
      public Builder clearVersion() {

        version_ = 0;
        onChanged();
        return this;
      }

      private Object serverName_ = "";
      /**
       * <code>string serverName = 4;</code>
       */
      public String getServerName() {
        Object ref = serverName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverName = 4;</code>
       */
      public Builder setServerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverName = 4;</code>
       */
      public Builder clearServerName() {

        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>string serverName = 4;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        serverName_ = value;
        onChanged();
        return this;
      }

      private Object apiUrl_ = "";
      /**
       * <code>string apiUrl = 5;</code>
       */
      public String getApiUrl() {
        Object ref = apiUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          apiUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string apiUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getApiUrlBytes() {
        Object ref = apiUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          apiUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string apiUrl = 5;</code>
       */
      public Builder setApiUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        apiUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string apiUrl = 5;</code>
       */
      public Builder clearApiUrl() {

        apiUrl_ = getDefaultInstance().getApiUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string apiUrl = 5;</code>
       */
      public Builder setApiUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        apiUrl_ = value;
        onChanged();
        return this;
      }

      private Object method_ = "";
      /**
       * <code>string method = 6;</code>
       */
      public String getMethod() {
        Object ref = method_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 6;</code>
       */
      public Builder setMethod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 6;</code>
       */
      public Builder clearMethod() {

        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 6;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        method_ = value;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>string ip = 7;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ip = 7;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 7;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 7;</code>
       */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 7;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 8;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 8;</code>
       */
      public Builder setPort(int value) {

        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 8;</code>
       */
      public Builder clearPort() {

        port_ = 0;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.cn.weit.happymo.message.State state = 9;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <code>.cn.weit.happymo.message.State state = 9;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.weit.happymo.message.State state = 9;</code>
       */
      public ServerState.State getState() {
        @SuppressWarnings("deprecation")
        ServerState.State result = ServerState.State.valueOf(state_);
        return result == null ? ServerState.State.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.weit.happymo.message.State state = 9;</code>
       */
      public Builder setState(ServerState.State value) {
        if (value == null) {
          throw new NullPointerException();
        }

        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.weit.happymo.message.State state = 9;</code>
       */
      public Builder clearState() {

        state_ = 0;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <code>int64 updateTime = 10;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>int64 updateTime = 10;</code>
       */
      public Builder setUpdateTime(long value) {

        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updateTime = 10;</code>
       */
      public Builder clearUpdateTime() {

        updateTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> map_;
      private com.google.protobuf.MapField<String, String>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */

      public boolean containsMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getMap() {
        return getMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */

      public java.util.Map<String, String> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */

      public String getMapOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */

      public String getMapOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        internalGetMutableMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */

      public Builder removeMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */
      public Builder putMap(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map = 11;</code>
       */

      public Builder putAllMap(
          java.util.Map<String, String> values) {
        internalGetMutableMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.weit.happymo.message.MoRequestMsg)
    }

    // @@protoc_insertion_point(class_scope:cn.weit.happymo.message.MoRequestMsg)
    private static final MoRequest.MoRequestMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MoRequest.MoRequestMsg();
    }

    public static MoRequest.MoRequestMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoRequestMsg>
        PARSER = new com.google.protobuf.AbstractParser<MoRequestMsg>() {
      @Override
      public MoRequestMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MoRequestMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MoRequestMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MoRequestMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public MoRequest.MoRequestMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_weit_happymo_message_MoRequestMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_weit_happymo_message_MoRequestMsg_MapEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_weit_happymo_message_MoRequestMsg_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017MoRequest.proto\022\027cn.weit.happymo.messa" +
      "ge\032\rMsgType.proto\032\013State.proto\"\333\002\n\014MoReq" +
      "uestMsg\022\r\n\005msgId\030\001 \001(\005\0221\n\007msgType\030\002 \001(\0162" +
      " .cn.weit.happymo.message.MsgType\022\017\n\007ver" +
      "sion\030\003 \001(\005\022\022\n\nserverName\030\004 \001(\t\022\016\n\006apiUrl" +
      "\030\005 \001(\t\022\016\n\006method\030\006 \001(\t\022\n\n\002ip\030\007 \001(\t\022\014\n\004po" +
      "rt\030\010 \001(\005\022-\n\005state\030\t \001(\0162\036.cn.weit.happym" +
      "o.message.State\022\022\n\nupdateTime\030\n \001(\003\022;\n\003m" +
      "ap\030\013 \003(\0132..cn.weit.happymo.message.MoReq" +
      "uestMsg.MapEntry\032*\n\010MapEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001B\013B\tMoRequestP\000P\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MsgTypeEnum.getDescriptor(),
          ServerState.getDescriptor(),
        }, assigner);
    internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_weit_happymo_message_MoRequestMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor,
        new String[] { "MsgId", "MsgType", "Version", "ServerName", "ApiUrl", "Method", "Ip", "Port", "State", "UpdateTime", "Map", });
    internal_static_cn_weit_happymo_message_MoRequestMsg_MapEntry_descriptor =
      internal_static_cn_weit_happymo_message_MoRequestMsg_descriptor.getNestedTypes().get(0);
    internal_static_cn_weit_happymo_message_MoRequestMsg_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_weit_happymo_message_MoRequestMsg_MapEntry_descriptor,
        new String[] { "Key", "Value", });
    MsgTypeEnum.getDescriptor();
    ServerState.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
