// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgType.proto

package cn.weit.happymo.message;

public final class MsgTypeEnum {
  private MsgTypeEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code cn.weit.happymo.message.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTBEAT = 0;</code>
     */
    HEARTBEAT(0),
    /**
     * <code>SERVER = 1;</code>
     */
    SERVER(1),
    /**
     * <code>API = 2;</code>
     */
    API(2),
    /**
     * <code>GOSSIP_PING = 3;</code>
     */
    GOSSIP_PING(3),
    /**
     * <code>GOSSIP_SYNC = 4;</code>
     */
    GOSSIP_SYNC(4),
    /**
     * <code>GOSSIP_REQ = 5;</code>
     */
    GOSSIP_REQ(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HEARTBEAT = 0;</code>
     */
    public static final int HEARTBEAT_VALUE = 0;
    /**
     * <code>SERVER = 1;</code>
     */
    public static final int SERVER_VALUE = 1;
    /**
     * <code>API = 2;</code>
     */
    public static final int API_VALUE = 2;
    /**
     * <code>GOSSIP_PING = 3;</code>
     */
    public static final int GOSSIP_PING_VALUE = 3;
    /**
     * <code>GOSSIP_SYNC = 4;</code>
     */
    public static final int GOSSIP_SYNC_VALUE = 4;
    /**
     * <code>GOSSIP_REQ = 5;</code>
     */
    public static final int GOSSIP_REQ_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return HEARTBEAT;
        case 1: return SERVER;
        case 2: return API;
        case 3: return GOSSIP_PING;
        case 4: return GOSSIP_SYNC;
        case 5: return GOSSIP_REQ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MsgTypeEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cn.weit.happymo.message.MsgType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMsgType.proto\022\027cn.weit.happymo.message" +
      "*_\n\007MsgType\022\r\n\tHEARTBEAT\020\000\022\n\n\006SERVER\020\001\022\007" +
      "\n\003API\020\002\022\017\n\013GOSSIP_PING\020\003\022\017\n\013GOSSIP_SYNC\020" +
      "\004\022\016\n\nGOSSIP_REQ\020\005B\rB\013MsgTypeEnumb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
