server:
  port: 8000
  servlet:
    context-path: /ccs
  name: weit0
  ip: 192.168.0.1

internal:
  server:
    netty:
      port: 18000
    num: 3
    max: 300

external:
  server:
    netty:
      port: 18001
    max: 300

logging:
  file: ../logs/cc-server.log
  level:
    org.springframework: INFO
    cn.weit.happymo: DEBUG
    cn.hx.mall.dao: DEBUG
    com.baomidou.dynamic: DEBUG
